- css/styles1.css
normal
upon hover
same type of hover animation as it was for the hackathons
> month highlight

- index3.html
- styles1.css
I have added scrolling effect on contact us and linked with the contact section.some code is commented out in the script section as it is bugy.
Thank You
Hrishikesh Agarwal.
> Contact us activated

- css/styles1.css
> horizontal scrolling

- index3.html
- styles1.css
I have added scroll effect in contact section and rectified the footer position.
> issue resolved

- css/styles.css
- index3.html
Fixes: #27 
Background for the time seems pretty nice to me. In future if we plan to change the layout we can implement it. @Amankumar29
Please Review @aryamanpuri and suggest changes :)
> refactor: only one month per slide

- css/styles1.css
- index.html
#18 @aryamanpuri  @aashimgarg  please review.
> Fonts and footer fixed

- README.md
adds images to the readme.md #22
> images work now, check the preview

- css/styles1.css
- index.html
> Added links to all opensource events and hackathons.

- README.md
> docs: added updation steps in Readme

- css/styles1.css
- index.html
The alignment of footer content is rectified for large resolutions screen.
Fixes #38 
- Code
It has been rigorously tested on different resolutions of desktop devices available using http://re-view.emmet.io.
> Footer alignment

- contact.html
- css/contact.css
- index.html
contact page with contact forum including (name , email ,text content)
linked the contact us button of home page to the footer area of the home page instead of the new contact us page
Fixes #26  [ISSUE]
- Code
tested on my local system 
screenshots
> Contact page added

- README.md
Update remote URL in README.md to point to present repo
Fixes #63
> Update remote URL

- css/styles1.css
- index.html
made the footer small
Fixes #60  [ISSUE]
- Code
screenshots
> made footer small

- team.css
background of navbar changed to grey
Fixes #71 
- Code
Tested on my local system
> Navbar made grey

- team.css
Heading changed to white and padding added at the top.
Fixes #79 
- Code
Tested on the local environment.
> heading color changed

- about.html
about us footer same as home page
Fixes #82 [ISSUE]
- Code
system test.
> about us footer

- about.html
- contact.html
- index.html
Navbar links added in about.html,index.html and contact.html
Fixes #74 
- Code
Tested locally.
> Navbar-links addded

- css/styles1.css
Height of title id change to 660px to solve the issue.
Fixes #81 
- Code
Tested in the local environment.
> Height of title changed

- about.html
- contri.html
Month section linked to the navbar in the team and about us page.
Fixes #88
- Code
Tested on local environment
> Month linked to team and about us page

- team.css
Team alignment was messed up earlier.
Fixes # [90]
Team alignment is fixed now. 
Also added proper indentation for all the code in this CSS file.
Spacing fixed.
> Team page alignment fixed and spacing in the code

- team.css
Reverts Catalyst-CSE/OpenSourceEvents-Frontend#95
> Revert "Team page alignment fixed and spacing in the code"

- about.html
Contact us option in about us navbar linked to the homepage footer.
Fixes #87 
- Code
Checked locally
> contact us linked to footer

- about.html
- contact.html
- contri.html
- index.html
Contact form linked to the homepage, about page and team page navbar
Fixes #100 
- Code
Tested locally
> Contact form linked

- css/styles1.css
Arrow made to center.
Fixes #98 
- Code
Tested locally.
> Allignment fixed for button

- contact.html
- css/contact.css
Fixes #108 
- Code
- Outreach
Tested locally
> Contact page fixed

- README.md
- css/contact.css
- css/styles1.css
- index.html
- scroll.js
- team.css
the image on the landing page was overflowing as there was a css flaw in which the image was hard coded to be of 660px. hence behaving differently on different screen resolution. i have wrapped it in a div and made it dynamic in nature, hence it will change according to screen resolution.
Fixes #81  [ISSUE]
- Code
tested on my machine 1920x1080 resolution
1224x947 resolution 
996x800ish resolution
> fixed image size issue on home page

- contri.html
- team.css
Aligned team page according to hierarchy.
Fixes #90 
- Code
- Outreach
> Team page alignment

- contact.html
- rj.css
Added contact form validation.
Name: Accepts only alphabets
Email: Accepts only email ID
Number: Accepts only number (max 15 digits)
Message: Accepts characters (max 100)
Cleaned the code using Prettier.
> Contact form validation added

- contact.html
- rj.css
Reverts Catalyst-IN/OpenSourceEvents-Frontend#114
> Revert "Contact form validation added"

- index.html
Added MLH Fellowship in the May month.
Fixes #116
> added MLH Fellowship

- contact.html
- rj.css
- Name requires only alphabets
- Email Address requires only proper format
- Phone Number requires only numbers
Fixes #96
> Contact form validation

- months.css
Removed black border on the months and instead added a box-shadow.
- Code
> UI Improvement add box-shadow to months instead of border radius

- index.html
- months.css
> Added Margin to avoid overlapping of month with footer in mobile view 

- css/styles1.css
- index.html
> space footer contents

- css/styles1.css
- index.html
Fixes #19 
- Code
- Outreach
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
> Mobile View Responsive

- index.html
Add hover feature for every event so we provide information about that event. 
- Code
> Adding new feature for events

- index.html
Google Analytics added 
Fixes # 115
- Code
- Outreach
locally
> Google analytics added

- index.html
Adding a pop-up box, which will appear on clicking the submit button of subscription to the newsletter. This will make the website more interactive with the user.
> Adding a pop-up on subscribing to newsletter

- index.html
Replacing the emoji code by emoji.
> Error while displaying the smiley emoji

- index.html
Fixes #134 
- Code
- Outreach
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
> Added hover to events

- index.html
[x] Removed GCI from timeline
Fixes #139 
[x] code
NOTE : Documentation update is required
> Removed GCI & updated timeline

- about.html
- index.html
There were some issues in the JavaScript code in index.html (were listed as Indentation and javascript issues in index.html), the issue was with closing of braces , and has been fixed.
Fixes # [ISSUE:Indentation and javascript issues in index.html]
-> Code(Fixed indentation bug)
> Javascript bug fixed

- index.html
> Issue #145 Solved

- css/styles1.css
- index.html
Added famous quotes of Steve Jobs on the space between month and footer. And the quote is changing after 10 seconds.
Fixes #144 
- Code
> Added Text transition

- index.html
- scroll.js
`About the issue`: On hovering over the event name, the event description was flickering. 
`Fix`:  I have introduced some javascript functions inside `Scroll.js` & accordingly modified the `index.html` file.
Fixes # [143]
- Code
I have tested it by hovering over each event name of each month.
Let me know if you need any more changes in this part!
> Fixed the 'on Hover' bug

- index.html
Added 3 events (i.e. DevScript WOC, SWOC and CWOC) in the list according to month.
Fixes #146
> Added 3 events

- css/styles1.css
- index.html
Added few more quotes in Array and used random modifier
Changed Quote font to Lora
> Added Steve Jobs Quotes

- css/styles1.css
- index.html
Pull Request for Issue #155 : Add Steve Jobs quotes.
I added a Steve Jobs quote next to the footer and removed useless br tags.
Preview :
> Fixed Issue #155 : Add Steve Jobs quotes

- css/styles1.css
- index.html
Fixes #156 
Changed the font to Poppins.
> Changed Fonts

- index.html
- months.css
Fixes  #147 
- Code
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
> fixed the footer and made website responsive

- .github/config.yml
I have added a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
Fixes #157  [ISSUE]
- Code
- Outreach
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
This has been self-tested by me.
> Add Config Files for Welcome Bot
